config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Root handles user login or will redirect to create a new user
  root 'welcome#landing_page'

  #Login Routes
  post '/signin', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create_facebook'
  #Logout Routes
  get 'logout', to: 'sessions#destroy'


  resources :users do
    resource :profile
    resources :recipes, only: [:show, :index, :new]
  end
  #resources :profiles
  resources :recipes, except: [:show, :index, :new, :under500] do
    member do
      get :under500
      get :carbs_under_30
    end
  end
  resources :menus
end

app/models/menu.rb
class Menu < ApplicationRecord

  # <- Start Associations->
  belongs_to :user
  has_many :meals, -> { order(:date) }, inverse_of: :menu, dependent: :destroy
  has_many :recipes, through: :meals
  accepts_nested_attributes_for :meals
  # <-End Associations->

  # <-Start Validations->
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true
  # <- End Validations ->

  # <- Start Security ->

  # <- End Security ->

  # <- Start Methods ->
  def build_menu
    collect_recipes
    (start_date..end_date).each do |date|
      meals.build(date: date, recipe_id: @recipes.sample)
    end
  end

  def collect_recipes
    @recipes = Recipe.all.pluck(:id)
  end
  # <- End Methods ->
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :require_login
  before_action :set_user
  layout 'profile-layout'

  def new
    @menu = @user.menus.build(start_date: params[:start_date] || Date.today, end_date: params[:end_date] || 6.days.from_now.to_date)
    @menu.build_menu
  end

  def create
  @menu = current_user.menus.build(menu_params)
    if @menu.save
      redirect_to menu_path(@menu)
    else
      render :new
    end
  end

  def show
    @menu = @user.menus.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @menu}
    end
  end

  #Rendering every menu created by the user
  def index
    @menus = @user.menus.all
    render json: @menus
  end

  private

  def set_user
    @user = current_user
  end

  def menu_params
    params.require(:menu).permit(:start_date, :end_date, meals_attributes: [:id, :date, :recipe_id])
  end

end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for @menu do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <div class="meal">
        <%= meal_fields.hidden_field :id %>
        <%= meal_fields.hidden_field :date %>
        <p><%= meal_fields.object.date.to_s %></p>
        <div class="form-control">
          <%= meal_fields.label :recipe_id %>
          <%= meal_fields.select :recipe_id, current_user.recipe_options %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/new.html.erb
<h1>New Menu for <%= @user.first_name %></h1>

<%= form_for @menu, url: new_menu_path, method: "GET" do |form| %>
  <div class="form-control">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, type: "date" %>
  </div>

  <div class="form-control">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, type: "date" %>
  </div>

  <div class="action">
    <%= form.submit "Generate Plan" %>
  </div>
<% end %>

<%= render partial: "form" %>

app/views/menus/show.html.erb
<div class="menu-box">
  <%= @menu.meals.each do |meal| %>
    <div class="individual-recipe-from-menu">
      <h3><%= meal.date.strftime("%A, %d/%m/%Y") %></h3>
      <h3><%= meal.recipe.name %></h3>
      <p><%= meal.recipe.description %></p>
    </div>
  <% end %>
</div>
</div>