config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Root handles user login or will redirect to create a new user
  root 'welcome#landing_page'

  #Login Routes
  post '/signin', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create_facebook'
  #Logout Routes
  get 'logout', to: 'sessions#destroy'


  resources :users do
    resource :profile
    resources :recipes, only: [:show, :index, :new]
  end
  #resources :profiles
  resources :recipes, except: [:show, :index, :new, :under500] do
    member do
      get :under500
      get :carbs_under_30
    end
  end
  resources :menus
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # <- Start Associations->
  belongs_to :user
  # <-End Associations->

  # <-Start Validations->
  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :description, presence: true
  validates :calories, presence: true
  validates :carbs, presence: true
  validates :protein, presence: true
  validates :fats, presence: true
  validates :user, presence: true
  # <- End Validations ->

  # <- Start Scope Queries ->
  def self.find_under_500
    where('calories <= ?', 500)
  end

  def self.find_recipe_carbs_under_30
    where("carbs <= ?", 30)
  end
  # <- End Scope Queries ->


  # <- Start Security ->

  # <- End Security ->

  # <- Start Methods ->
  # <- End Methods ->
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login
  before_action :set_user
  layout 'profile-layout'

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    render json: @recipe, status: 201
  end

  def index
    @recipes = Recipe.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @recipes}
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    creator = @recipe.user
    @creator = creator.first_name
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @recipe}
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(recipe_params)
      redirect_to user_recipes_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path(@recipe), notice: "Deleted Recipe: #{recipe.name}"
  end

  def under500
    @recipes500 = Recipe.find_under_500
  end

  def carbs_under_30
    @recipes_under_30 = Recipe.find_recipe_carbs_under_30
  end



  private

  def set_user
    @user = current_user
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :calories, :carbs, :protein, :fats, :user_id)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="recipe-form">
<%= form_for @recipe do |form| %>

<%= form.hidden_field :user_id, value: @user.id %>

  <div class="recipe-form-group">
    <%= form.text_field :name, :placeholder => "Name" %>
  </div>

  <div class="recipe-form-group">
    <%= form.text_area :description, :placeholder => "Description" %>
  </div>

  <div class="recipe-form-group">
    <%= form.number_field :calories, :placeholder => "Calories" %>
  </div>

  <div class="recipe-form-group">
    <%= form.number_field :carbs, :placeholder => "Carbs" %>
  </div>

  <div class="recipe-form-group">
    <%= form.number_field :protein, :placeholder => "Protein" %>
  </div>

  <div class="recipe-form-group">
    <%= form.number_field :fats, :placeholder => "Fats" %>
  </div>
  <div class="recipe-submit-button">
    <%= form.submit%>
    </div>
<% end %>
</div>

app/views/recipes/carbs_under_30.html.erb
<h1>Recipes Under 30 Carbs</h1>
<div>
  <% @recipes_under_30.each do |recipe| %>
    <div class="individual-recipe">
      <h3><%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe.id) %></h3>
      <p><%= recipe.description %></p>
      <p>Calories: <%= recipe.calories %></p>
      <p>Carbs: <%= recipe.carbs %></p>
      <p>Protein: <%= recipe.protein %></p>
      <p>Fats: <%= recipe.fats %></p>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li><%= link_to "Delete", user_recipe_path(recipe.user_id, recipe.id), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?"
        }, method: :delete %></li>
      </ul>
    </div>
  <% end %>
  </div>

app/views/recipes/edit.html.erb
<div class="edit-recipe-container">
<h1>Edit Recipe</h1>

<%= render partial: "recipes/form" %>

</div>

app/views/recipes/index.html.erb
<h1><%= @user.first_name%>'s Recipes</h1>
<div class="under-500-button">
  <h3><%=link_to "Recipes Under 500 Calories", under500_recipe_path(@user)%></h3>
</div>
  <% @recipes.each do |recipe| %>
    <div class="individual-recipe">
      <h3><%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe.id) %></h3>
      <p><%= recipe.description %></p>
      <p>Calories: <%= recipe.calories %></p>
      <p>Carbs: <%= recipe.carbs %></p>
      <p>Protein: <%= recipe.protein %></p>
      <p>Fats: <%= recipe.fats %></p>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li><%= link_to "Delete", user_recipe_path(recipe.user_id, recipe.id), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?"
        }, method: :delete %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe-container">
<h1>Create A Recipe</h1>

<%= render partial: "recipes/form" %>

</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Description:</h2>
<p><%= @recipe.description %></p>

<h2>Calories:</h2>
<p><%= @recipe.calories %></p>

<h2>Carbs:</h2>
<p><%= @recipe.carbs %></p>

<h2>Protein:</h2>
<p><%= @recipe.protein %></p>

<h2>Fats:</h2>
<p><%= @recipe.fats%></p>

<h2>Created By:</h2>
<p><%= @creator %></p>


<div>
  <ul class="recipe-actions">
    <li><%= link_to "Back", user_recipes_path %></li>
    <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
    <li><%= link_to "Delete", user_recipe_path(@recipe.user_id, @recipe.id), method: :delete %></li>
  </ul>
</div>

app/views/recipes/under500.html.erb
<h1>Recipes Under 500 Calories</h1>
<div>
  <% @recipes500.each do |recipe| %>
    <div class="individual-recipe">
      <h3><%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe.id) %></h3>
      <p><%= recipe.description %></p>
      <p>Calories: <%= recipe.calories %></p>
      <p>Carbs: <%= recipe.carbs %></p>
      <p>Protein: <%= recipe.protein %></p>
      <p>Fats: <%= recipe.fats %></p>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li><%= link_to "Delete", user_recipe_path(recipe.user_id, recipe.id), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?"
        }, method: :delete %></li>
      </ul>
    </div>
  <% end %>
  </div>