config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Root handles user login or will redirect to create a new user
  root 'welcome#landing_page'

  #Login Routes
  post '/signin', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create_facebook'
  #Logout Routes
  get 'logout', to: 'sessions#destroy'


  resources :users do
    resource :profile
    resources :recipes, only: [:show, :index, :new]
  end
  #resources :profiles
  resources :recipes, except: [:show, :index, :new, :under500] do
    member do
      get :under500
      get :carbs_under_30
    end
  end
  resources :menus
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/landing_page.html.erb
<div class="landing-page">
  <div class="landing-column">
    <div class="welcome-text-box">
      <h1>Piatto</h1>
      <h2>Plan a Menu</h2>
    </div>
  </div>

<div class="landing-column">
  <div class="login-box">
    <h2>Please Sign In </h2>
    <div class="user-login-errors">
      <% flash.each do |key, value| %>
        <%= value %>
    <% end %>
  </div>
      <%= form_for(:session, url: signin_path, :html => {:class => 'form-control'})do |f| %>
        <div class="login-text-field">
          <%= f.text_field :email, :placeholder => "Email" %>
        </div>
        <br>
        <div class="login-text-field">
          <%= f.password_field :password, :placeholder => "Password"%>
        </div>
        <br>
        <div class="login-button">
          <%= f.submit "Login", :class => "login-button"%>
        </div>
      <% end %>
      <div class= "facebook-login">
        <%=link_to "Login via Facebook", "/auth/facebook"%>
      </div>
        <div class="new-user-route">
          <p>Not registered? <%= link_to "Sign Up!", new_user_path %></p>
        </div>
      </div>
    </div>
</div>